# "--since" can use this property to match (top > bottom) a remote target to check the differences.
changesetBaseRefs:
  - master
  # Developers should use upstream first, origin is a fork that could be outdated.
  # - upstream/master
  - origin/master

defaultSemverRangePrefix: ""

enableTelemetry: false

# npmScopes:
# initScope:
# initFields:

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.2.2.cjs
